name: lmsify
publish_to: none
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_serialize: ^2.0.0
  angel_framework: ^2.0.0
  angel_file_service: ^2.0.0
  angel_jael: ^2.0.0
  angel_static: ^2.0.0
  angel_configuration: ^2.0.0
dev_dependencies:
  angel_serialize_generator: ^2.0.0
  build_runner: ^1.0.0
